name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (optional, will use tag if not provided)'
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx nx run-many -t test --all --parallel=3

      - name: Run linting
        run: npx nx run-many -t lint --all --parallel=3

  build-and-publish:
    runs-on: ubuntu-latest
    needs: test
    environment: npm-publish
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@elloloop'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Version packages (if manual trigger)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version
        run: |
          npx nx release version ${{ github.event.inputs.version }} --dry-run=false

      - name: Build packages
        run: npx nx run-many -t build -p core,shared,react,angular --parallel=3
          
      - name: Publish to GitHub Packages
        run: |
          # Configure npm authentication
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@elloloop:registry=https://npm.pkg.github.com" >> ~/.npmrc
          
          # Publish packages in dependency order
          cd dist/libs/shared && npm publish --provenance
          cd ../../../dist/libs/core && npm publish --provenance
          cd ../react && npm publish --provenance
          cd ../angular && npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Published packages to GitHub Packages Registry
            - Built with Node.js 20 and latest dependencies
            
            ## Published Packages
            - @elloloop/xinglish-shared@${{ github.ref_name }}
            - @elloloop/xinglish-core@${{ github.ref_name }}
            - @elloloop/xinglish-react@${{ github.ref_name }}
            - @elloloop/xinglish-angular@${{ github.ref_name }}
          draft: false
          prerelease: false 